sudo: required
services:
  - docker
  
before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run docker-react npm test -- --coverage

language: node_js

node_js:
  - "10.14.2"

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-464221629897"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
